# Site settings
title: "Ravelys"
description: "I won a minigame in EVERY Mario Party EVER!. It’s teddy bear I usually hug it when I go to bed. What if YOU CREATE MUTANT GUMMY BEAR in Minecraft ? USING A RADIATION and POSION LIQUID minion"
url: "https://ravelys.github.io"  

title_slog: "" # 
title_sep: "" # 
# verification
bing: ""
yandex: ""
google: ""
# encoding timezone
encoding: "utf-8"
timezone: UTC
# Build settings
baseurl: / # leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:slug.html
sitemap_limit: 150.0
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"
